### PR TITLE
Add proposal for new page elements JSON structure

### PR DESCRIPTION
**Pull request by melvinsoft**
The following doc is the proposal of how to modify the page elements JSON structure to support multilingual content in Tahoe.

### CODE REVIEW

**Review by grozdanowski — APPROVED** [review]
Looks good. Requesting additional check from Filip and Anders.

**Comment by OmarIthawi** [comment]
@melvinsoft I can take a look on Monday. Unless you need to make this happen sooner.

**Review by bezidejni — APPROVED** [review]
LGTM

**Review by thraxil — APPROVED** [review]
I agree with the decision to put the language at the top level.

Ideally, the React code can be written to always default to the entry in `en`.

To mitigate the risk of languages getting out of sync, it also wouldn't be too hard to write our own small linter that goes through the languages in the JSON and either warns when there aren't corresponding entries for all languages or automatically inserts the empty ones when necessary. If these JSON objects or the data they are being generated from are being edited by hand, it would be easy to accidentally have a typo in a key that resulted in some hard to debug errors (eg, someone names a key "chlldren" in one of the language sections). Running some kind of automated sanity check when the JSON is generated would be nice.

**Review by OmarIthawi — APPROVED** [review]
Thanks @melvinsoft! Ditto to what Anders said.

**Comment by melvinsoft** [comment]
Thanks everyone for reviewing this PR. @thraxil I added your sanity check proposal to the doc, so we make sure we implement it.

**Pull request merged**
